name: movie_review_app
description: A new base project using bloc, Clean Architecture on Flutter 3.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  auto_route: ^5.0.2
  cached_network_image: ^3.2.1
  camerawesome: ^0.3.3
  connectivity_plus: ^3.0.2
  copy_with_extension: ^4.0.2
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  device_preview: ^1.1.0
  dio: ^4.0.6
  easy_localization: ^3.0.1
  equatable: ^2.0.3
  event_bus: ^2.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_dotenv: ^5.0.2
  flutter_gen: ^5.1.0+1
  flutter_image_compress: ^1.1.3
  flutter_launcher_icons: ^0.11.0
  flutter_local_notifications: ^12.0.3
  flutter_native_splash: ^2.2.15
  flutter_rating_bar: ^4.0.1
  flutter_screenutil: ^5.5.3+2
  flutter_slidable: ^2.0.0
  flutter_staggered_grid_view: ^0.6.2
  flutter_svg: ^1.1.0
  freezed_annotation: ^2.0.3
  get_it: ^7.2.0
  infinite_scroll_pagination: ^3.2.0
  injectable: ^1.5.3
  json_annotation: ^4.5.0
  logger: ^1.1.0
  path_provider: ^2.0.11
  photo_view: ^0.14.0
  retrofit: ^3.3.0
  rxdart: ^0.27.5
  shared_preferences: ^2.0.15
  shimmer: ^2.0.0
  top_snackbar_flutter: ^2.1.1

dev_dependencies:
  auto_route_generator: ^5.0.2
  build_runner: ^2.1.11
  copy_with_extension_gen: ^4.0.2
  flutter_gen_runner: ^5.1.0+1
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.0.3+1
  injectable_generator: ^1.5.3
  json_serializable: ^6.2.0
  retrofit_generator: ^4.2.0

flutter_gen:
  output: lib/gen/
  line_length: 80

  integrations:
    flutter_svg: true

  assets:
    enable: true
    package_parameter_enabled: true

  font:
    enable: true

flutter:
  uses-material-design: true
  assets:
    - assets/translations/
    - assets/env/
    - assets/svg/
    - assets/images/

  fonts:
    - family: Lexend
      fonts:
        - asset: assets/font/Lexend-Light.ttf
          weight: 300
        - asset: assets/font/Lexend-Regular.ttf
          weight: 400
        - asset: assets/font/Lexend-Medium.ttf
          weight: 500
        - asset: assets/font/Lexend-Bold.ttf
          weight: 700

flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icon/logo2.png"
  adaptive_icon_background: null
